services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: sweatbot_postgres
    environment:
      POSTGRES_DB: hebrew_fitness
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitness_user -d hebrew_fitness"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: sweatbot_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes --requirepass sweatbot_redis_pass

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local