[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "sweatbot-api"

[services.variables]
PORT = "8000"
PYTHON_VERSION = "3.11"