# Points Rules Configuration
# Defines bonus points and multipliers based on conditions
# Rules are evaluated in order and all matching rules apply

version: "3.0"
last_updated: "2025-01-10"

rules:
  # Bonus Rules (add fixed points)
  high_rep_bonus:
    id: "high_rep_bonus"
    name: "High Rep Bonus"
    name_he: "בונוס חזרות גבוה"
    description: "Bonus for exercises with 20+ reps"
    description_he: "בונוס לתרגילים עם 20+ חזרות"
    rule_type: bonus
    condition: "reps >= 20"
    value: 50
    enabled: true
    priority: 1

  weight_bonus:
    id: "weight_bonus"
    name: "Weighted Exercise Bonus"
    name_he: "בונוס תרגיל עם משקל"
    description: "Bonus for any weighted exercise"
    description_he: "בונוס לכל תרגיל עם משקל"
    rule_type: bonus
    condition: "weight_kg > 0"
    value: 30
    enabled: true
    priority: 2

  personal_record_bonus:
    id: "personal_record_bonus"
    name: "Personal Record Bonus"
    name_he: "בונוס שיא אישי"
    description: "Bonus for setting new personal records"
    description_he: "בונוס על קביעת שיא אישי חדש"
    rule_type: bonus
    condition: "is_personal_record == true"
    value: 100
    enabled: true
    priority: 3

  endurance_bonus:
    id: "endurance_bonus"
    name: "Endurance Bonus"
    name_he: "בונוס סיבולת"
    description: "Bonus for exercises lasting 5+ minutes"
    description_he: "בונוס לתרגילים של 5+ דקות"
    rule_type: bonus
    condition: "duration_seconds >= 300"
    value: 75
    enabled: true
    priority: 4

  # Multiplier Rules (multiply current points)
  heavy_weight_multiplier:
    id: "heavy_weight_multiplier"
    name: "Heavy Weight Multiplier"
    name_he: "מכפיל משקל כבד"
    description: "1.5x multiplier for 50kg+ exercises"
    description_he: "מכפיל של 1.5 לתרגילים של 50+ ק\"ג"
    rule_type: multiplier
    condition: "weight_kg >= 50"
    value: 1.5
    enabled: true
    priority: 5

  streak_multiplier:
    id: "streak_multiplier"
    name: "Streak Multiplier"
    name_he: "מכפיל רצף"
    description: "1.2x multiplier for 7+ day streaks"
    description_he: "מכפיל של 1.2 לרצפים של 7+ ימים"
    rule_type: multiplier
    condition: "streak_days >= 7"
    value: 1.2
    enabled: true
    priority: 6

  combo_multiplier:
    id: "combo_multiplier"
    name: "Combo Multiplier"
    name_he: "מכפיל קומבו"
    description: "1.3x multiplier for 5+ exercises in one session"
    description_he: "מכפיל של 1.3 ל-5+ תרגילים בסשן אחד"
    rule_type: multiplier
    condition: "session_exercise_count >= 5"
    value: 1.3
    enabled: true
    priority: 7

# Rule evaluation notes:
# - Bonus rules add fixed points to total
# - Multiplier rules multiply the current point total
# - All matching rules apply (not mutually exclusive)
# - Priority determines evaluation order (lower = earlier)
# - Conditions use Python-like syntax for evaluation
